export const CLEAR_DIRECTIONS = 'CLEAR_DIRECTIONS';
export const ROUTE_CALCULATION_COMPLETE = 'ROUTE_CALCULATION_COMPLETE';
export const ROUTE_CALCULATION_REQUEST = 'ROUTE_CALCULATION_REQUEST';
export const SET_DIRECTIONS = 'SET_DIRECTIONS';
export const SET_ROUTE_SELECTOR_PLACE = 'SET_ROUTE_SELECTOR_PLACE';
export const SET_ROUTE_SELECTOR_MAP = 'SET_ROUTE_SELECTOR_MAP';
export const SET_SERVICE = 'SET_SERVICE';
